[customizations.installer.kickstart]
contents = """
%post
# https://github.com/osbuild/bootc-image-builder/issues/780
bootc switch --mutate-in-place --transport registry zot-registry.apps.ocp.chrislab.geek.nz/fedora/router-bootc:latest
%end

network --bootproto=dhcp --device=link --activate --onboot=on

timezone Pacific/Auckland
lang en_NZ.UTF-8
keyboard us

user --name=chris --groups=wheel --plaintext --password=password
sshkey --username=chris "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIfbU7bHdYE5RWgZVb6Ix4tmhUE52XkJUTDguFXvZtXN chris@linux"
"""

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Localization",
    "org.fedoraproject.Anaconda.Modules.Storage",
    "org.fedoraproject.Anaconda.Modules.Network",
    "org.fedoraproject.Anaconda.Modules.Users",
    "org.fedoraproject.Anaconda.Modules.Timezone"
]
