FROM quay.io/fedora/fedora-bootc
#FROM quay.io/fedora/fedora-bootc:41

RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN dnf -y install \
        htop wget nload git vim-enhanced screen tmux rsync \
        # VM
        qemu-guest-agent \
        # Cockpit
        cockpit cockpit-files cockpit-machines cockpit-podman cockpit-selinux \
        # WiFi
        iw hostapd wireless-regdb wpa_supplicant NetworkManager-wifi iwl7260-firmware \
        # Network Tools
        tcpdump nmap iperf3 iptraf-ng iputils iproute bind-utils \
        traceroute net-tools mtr btop \
        # System
        lm_sensors net-snmp firewalld wireguard-tools tuned \
        usbutils pciutils samba && \

        # Swap ffmpeg
        dnf swap -y ffmpeg-free ffmpeg --allowerasing

RUN dnf -y install \
        # Desktop
        gnome-shell gdm gnome-terminal firefox nautilus gnome-system-monitor \
        file-roller gnome-tweaks @development-tools gdouros-symbola-fonts liberation-sans-fonts \
        liberation-fonts liberation-serif-fonts liberation-narrow-fonts liberation-mono-fonts \
        liberation-fonts-common google-noto-cjk-fonts google-noto-cjk-fonts-common google-noto-cjk-fonts-common f41-backgrounds-gnome vlc flatpak

RUN flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && \
    flatpak install -y flathub org.gnome.Extensions tv.plex.PlexHTPC

    # Correct permissions for swtpm
RUN chown -R tss:tss /var/lib/swtpm-localca && \

    # 45drives file sharing
    curl -sSL https://repo.45drives.com/lists/45drives.repo -o /etc/yum.repos.d/45drives.repo && \
    sed -i 's/enabled=1/enabled=0/g' /etc/yum.repos.d/45drives.repo && \
    dnf install -y --enable-repo=45drives_stable cockpit-file-sharing && \

    # LibreNMS agent
    curl -o /usr/bin/distro https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro && \
    chmod +x /usr/bin/distro

    # Enable services
RUN systemctl enable \
        snmpd \
        smb \
        hostapd \
        qemu-guest-agent \
        cockpit.socket \
        firewalld && \
    systemctl mask bootc-fetch-apply-updates.service && \
    
    # Clean up
    dnf clean all && \
    systemctl set-default multi-user.target && \
    sed -i 's/%wheel	ALL=(ALL)	ALL/%wheel	ALL=(ALL)	NOPASSWD: ALL/g' /etc/sudoers && \

    # Remove tuned profiles
    for i in accelerator-performance aws hpc-compute intel-sst latency-performance \
    network-latency network-throughput optimize-serial-console throughput-performance \
    virtual-host virtual-guest; \
        do if [ -d /usr/lib/tuned/profiles/$i ] ; then rm -rf /usr/lib/tuned/profiles/$i ; fi ; done

COPY etc /etc
RUN chmod 600 /etc/NetworkManager/system-connections/*.nmconnection
RUN bootc container lint
